[package]
authors = ["Peter Majchrak <petoknm@gmail.com>"]
name = "r2d2-mongodb"
version = "0.1.2"
description = "A MongoDB adaptor for r2d2 connection pool"
license = "GPL-3.0"
keywords = ["r2d2", "database", "mongo", "mongodb", "pool"]
readme = "README.md"
repository = "https://github.com/petoknm/r2d2-mongodb"
[dependencies]
mongodb = "0.3.7"
r2d2 = "0.8.2"
